"""Geography constants: countries, US states, international regions."""

COUNTRY_STANDARDIZATION = {
    'US': 'United States',
    'USA': 'United States',
    'Usa': 'United States',
    'United States': 'United States',
    'UK': 'United Kingdom',
    'United Kingdom': 'United Kingdom',
    'CAN': 'Canada',
    'Canada': 'Canada',
    'AUS': 'Australia',
    'Australia': 'Australia',
    'Germany': 'Germany',
    'DEU': 'Germany',
    'Deutschland': 'Germany',
    'FRA': 'France',
    'France': 'France',
    'ITA': 'Italy',
    'Italy': 'Italy',
    'RUS': 'Russia',
    'Russia': 'Russia',
    'ESP': 'Spain',
    'Spain': 'Spain',
    'NLD': 'Netherlands',
    'Nederland': 'Netherlands',
    'Netherlands': 'Netherlands',
    'POL': 'Poland',
    'Poland': 'Poland',
    'Polska': 'Poland',
    'SWE': 'Sweden',
    'Sweden': 'Sweden',
    'NOR': 'Norway',
    'Norway': 'Norway',
    'DNK': 'Denmark',
    'Denmark': 'Denmark',
    'FIN': 'Finland',
    'Finland': 'Finland',
    'Finalnd': 'Finland',
    'BEL': 'Belgium',
    'Belgium': 'Belgium',
    'Belgique': 'Belgium',
    'CHE': 'Switzerland',
    'Switzerland': 'Switzerland',
    'AUT': 'Austria',
    'Austria': 'Austria',
    'ISR': 'Israel',
    'Israel': 'Israel',
    'HUN': 'Hungary',
    'Hungary': 'Hungary',
    'UKR': 'Ukraine',
    'Ukraine': 'Ukraine',
    'CZE': 'Czech Republic',
    'Czech Republic': 'Czech Republic',
    'PRT': 'Portugal',
    'Portugal': 'Portugal',
    'GRC': 'Greece',
    'Greece': 'Greece',
    'IRL': 'Ireland',
    'Ireland': 'Ireland',
    'SGP': 'Singapore',
    'Singapore': 'Singapore',
    'Albany': 'United States',
}

STATE_NAME_TO_CODE = {
    'Alabama': 'AL', 'Alaska': 'AK', 'Arizona': 'AZ', 'Arkansas': 'AR',
    'California': 'CA', 'Colorado': 'CO', 'Connecticut': 'CT', 'Delaware': 'DE',
    'Florida': 'FL', 'Georgia': 'GA', 'Hawaii': 'HI', 'Idaho': 'ID',
    'Illinois': 'IL', 'Indiana': 'IN', 'Iowa': 'IA', 'Kansas': 'KS',
    'Kentucky': 'KY', 'Louisiana': 'LA', 'Maine': 'ME', 'Maryland': 'MD',
    'Massachusetts': 'MA', 'Michigan': 'MI', 'Minnesota': 'MN', 'Mississippi': 'MS',
    'Missouri': 'MO', 'Montana': 'MT', 'Nebraska': 'NE', 'Nevada': 'NV',
    'New Hampshire': 'NH', 'New Jersey': 'NJ', 'New Mexico': 'NM', 'New York': 'NY',
    'North Carolina': 'NC', 'North Dakota': 'ND', 'Ohio': 'OH', 'Oklahoma': 'OK',
    'Oregon': 'OR', 'Pennsylvania': 'PA', 'Rhode Island': 'RI', 'South Carolina': 'SC',
    'South Dakota': 'SD', 'Tennessee': 'TN', 'Texas': 'TX', 'Utah': 'UT',
    'Vermont': 'VT', 'Virginia': 'VA', 'Washington': 'WA', 'West Virginia': 'WV',
    'Wisconsin': 'WI', 'Wyoming': 'WY', 'District of Columbia': 'DC',
}

STATE_CODE_TO_NAME = {code: name for name, code in STATE_NAME_TO_CODE.items()}

CANADA_PROVINCES = {
    'Toronto': 'Ontario',
    'Montreal': 'Quebec',
    'Vancouver': 'British Columbia',
    'Calgary': 'Alberta',
    'Edmonton': 'Alberta',
    'Ottawa': 'Ontario',
    'Winnipeg': 'Manitoba',
    'Quebec City': 'Quebec',
    'Hamilton': 'Ontario',
    'Kitchener': 'Ontario',
    'London': 'Ontario',
    'Victoria': 'British Columbia',
    'Halifax': 'Nova Scotia',
    'Oshawa': 'Ontario',
    'Windsor': 'Ontario',
    'Saskatoon': 'Saskatchewan',
    'Regina': 'Saskatchewan',
    'Sherbrooke': 'Quebec',
    'St. John\'s': 'Newfoundland and Labrador',
    'Barrie': 'Ontario',
    'Richmond': 'British Columbia',
}

UK_REGIONS = {
    'London': 'England',
    'Manchester': 'England',
    'Birmingham': 'England',
    'Liverpool': 'England',
    'Leeds': 'England',
    'Sheffield': 'England',
    'Edinburgh': 'Scotland',
    'Glasgow': 'Scotland',
    'Bristol': 'England',
    'Cardiff': 'Wales',
    'Belfast': 'Northern Ireland',
    'Newcastle': 'England',
    'Nottingham': 'England',
    'Leicester': 'England',
    'Coventry': 'England',
    'Sipson': 'England',
}
